---
- name: Elasticsearch with custom configuration
  hosts: elastic_cluster_test
  become: yes
  roles:
    #expand to all available parameters
    - { role: elasticsearch, es_instance_name: "{{ hostvars.inventory_hostname }}",
    es_config: {
      network.host: "0.0.0.0",
      node.data: true,
      cluster.name: "custom-cluster",
      discovery.zen.ping.unicast.hosts: "ubuntu2:9300,ubuntu3:9300",
      http.port: 9200,
      transport.tcp.port: 9300,
      node.data: true,
      node.master: true,
      bootstrap.mlockall: true,
      discovery.zen.ping.multicast.enabled: false } 
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 256m
    es_plugins:
     - plugin: elasticsearch/license
       version: latest
    oracle_java: true
